### ISSUE TITLE
Rework Week display

### ISSUE THREAD

**Issue by Buldugmaster99** [H3rmt/Calendar#32]
**Describe the bug**
Appointment gets drawn over rest of the day in Week display, although end < 23:00

**To Reproduce**
1. Create a Appointment, only 1 day span, end < 23:00
2. Appointment gets drawn over rest of the day
3.  Create a Appointment, min 2 day span
4. gets drawn correctly to end hour

**Expected behavior**
Appointment should only be drawn to where it ends

**Comment by H3rmt** [comment]
close with pull request
